const translations = {
    es: {
        nav: { home: "Inicio", activities: "Actividades", faith: "Nuestra Fe", missionaries: "Misioneros", locations: "Ubicaciones", contact: "Contacto" },
        hero: { title: "Bienvenido a Busca Cristo", subtitle: "Venid a Cristo y perfeccionaos en Él", btnActivities: "Ver Actividades", btnLocations: "Encontrar Ubicación" },
        activities: { title: "Actividades de la Iglesia", intro: "Descubre las diversas actividades y programas disponibles en nuestras ubicaciones. Cada ubicación ofrece oportunidades únicas para el crecimiento espiritual, la hermandad y el servicio.", worship: { title: "Servicios de la Iglesia", desc: "Adoración dominical, reuniones de la santa cena y servicios devocionales especiales", btn: "Ver Actividades" }, youth: { title: "Servicios para Jóvenes", desc: "Actividades, campamentos y programas para jóvenes de 12 a 18 años", btn: "Ver Actividades" }, family: { title: "Actividades Familiares", desc: "Noche de hogar familiar, actividades y programas para todas las edades", btn: "Ver Actividades" }, education: { title: "Actividades para Jóvenes Adultos", desc: "Escuela Dominical, Instituto y otras oportunidades de aprendizaje", btn: "Ver Actividades" }, service: { title: "Clases de Inglés", desc: "Aprende inglés en un ambiente comunitario de apoyo con clases gratuitas para todos los niveles", btn: "Ver Actividades" }, other: { title: "Otras Oportunidades", desc: "Actividades y programas adicionales disponibles en nuestras ubicaciones", btn: "Ver Actividades" } },
        doctrine: { title: "Nuestra Fe y Doctrina", intro: "Aprende más sobre nuestras creencias y enseñanzas fundamentales. Haz clic en cualquier tema para explorar una comprensión más profunda de nuestra fe.", jesus: { title: "Jesucristo", desc: "Aprende sobre nuestro Salvador, Su Expiación y Su papel central en nuestra fe y salvación" }, bom: { title: "Libro de Mormón", desc: "Descubre otro testamento de Jesucristo y su importancia en nuestra comprensión del plan de Dios" }, families: { title: "Familias Eternas", desc: "Entiende cómo las familias pueden estar juntas para siempre a través de ordenanzas sagradas del templo" }, prophets: { title: "Profetas Vivientes", desc: "Aprende sobre la revelación moderna y cómo Dios nos habla a través de Sus siervos elegidos" }, baptism: { title: "Bautismo", desc: "Aprende sobre los primeros principios y ordenanzas del Evangelio de Jesucristo" }, salvation: { title: "Plan de Salvación", desc: "Explora el plan eterno de Dios para Sus hijos y nuestro propósito en esta vida" } },
        missionaries: { title: "Conoce a Nuestros Misioneros", heading: "Compartiendo el Evangelio de Jesucristo", p1: "Nuestros misioneros de tiempo completo son jóvenes dedicados que han elegido servir al Señor durante 18-24 meses. Vienen de todo el mundo para compartir el mensaje de Jesucristo y Su evangelio restaurado.", p2: "Estos misioneros están aquí para ayudarte a aprender sobre nuestras creencias, responder tus preguntas y brindar orientación espiritual. Ofrecen lecciones gratuitas sobre Jesucristo, el Libro de Mormón y cómo las familias pueden estar juntas para siempre.", btnMeet: "Reunirse con Misioneros", btnLearn: "Aprender Más en Línea", formTitle: "Reunirse con Misioneros", formDescription: "Completa el formulario a continuación y nuestros misioneros se pondrán en contacto contigo para programar una reunión.", nameLabel: "Nombre *", addressLabel: "Dirección *", learnAboutLabel: "¿Sobre qué te gustaría aprender más?", namePlaceholder: "Tu nombre", addressPlaceholder: "Tu dirección", learnAboutPlaceholder: "Cuéntanos qué te interesa aprender...", submitBtn: "Enviar Solicitud", successMessage: "¡Gracias! Nos pondremos en contacto contigo pronto." },
        locations: { title: "Encuentra una Iglesia Cerca de Ti", useLocation: "Usar Mi Ubicación", or: "o", placeholder: "Ingresa tu ciudad, dirección o código postal", findBtn: "Buscar Iglesia", openMaps: "Abrir en Google Maps", note: "Ingresa una ciudad específica en lugar de una región grande para obtener resultados más precisos." },
        contact: { title: "Contáctanos", heading: "Ponerse en Contacto", p: "Nos encantaría saber de ti y responder cualquier pregunta que puedas tener sobre nuestra iglesia o actividades.", phone: "+34 93 123 4567", email: "info@buscacristo.org", address: "123 Calle de la Fe, Barcelona, España", namePlaceholder: "Tu Nombre", emailPlaceholder: "Tu Email", messagePlaceholder: "Tu Mensaje", sendBtn: "Enviar Mensaje" },
        footer: { about: "Busca Cristo", aboutText: "Venid a Cristo y perfeccionaos en Él mediante la fe, el arrepentimiento, el bautismo y el don del Espíritu Santo.", quickLinks: "Enlaces Rápidos", resources: "Recursos", follow: "Síguenos", copyright: "© 2024 Busca Cristo - La Iglesia de Jesucristo de los Santos de los Últimos Días. Todos los derechos reservados." },
        modal: { close: "×", activityDetails: "Detalles de la Actividad", locationInfo: "Obtener Información Específica de la Ubicación", locationInfoDesc: "Para recibir horarios detallados e información para tu ubicación específica, por favor proporciona tu información de contacto a continuación.", firstName: "Nombre *", lastName: "Apellido *", email: "Correo Electrónico *", phone: "Número de Teléfono", firstNamePlaceholder: "Tu nombre", lastNamePlaceholder: "Tu apellido", emailPlaceholder: "Tu correo", phonePlaceholder: "Tu teléfono", preferredLocation: "Ubicación Preferida *", selectLocation: "Selecciona una ubicación", interests: "Actividades de Interés", worship: "Servicios de la Iglesia", youth: "Servicios para Jóvenes", family: "Actividades Familiares", education: "Educación Religiosa", service: "Clases de Inglés", other: "Otras Oportunidades", message: "Preguntas o Comentarios Adicionales", messagePlaceholder: "Por favor, háznoslo saber si tienes preguntas específicas sobre actividades o te gustaría saber más sobre algún programa en particular.", submitBtn: "Obtener Detalles de Ubicación", backToFaith: "Volver a Nuestra Fe" },
        breadcrumb: { home: "Inicio", faith: "Nuestra Fe" },
        activitiesDetail: { worship: { title: "Servicios de la Iglesia", desc: "Únete a nosotros cada semana para adorar, aprender y crecer en la fe. Nuestras reuniones incluyen servicios de la santa cena, Escuela Dominical y reuniones de sacerdocio y Sociedad de Socorro, con devocionales y reuniones de testimonios durante todo el año.", activities: [] }, youth: { title: "Actividades para Jóvenes", desc: "Para jóvenes de 12 a 18 años, ofrecemos actividades semanales edificantes, conferencias de jóvenes y campamentos de verano que construyen amistades, fe y confianza a través del servicio, el aprendizaje y la diversión.", activities: [] }, family: { title: "Actividades Familiares", desc: "Las familias pueden acercarse más a través de las noches de hogar familiar, proyectos de servicio y reuniones sociales que fortalecen la fe y la unidad. Los viajes al templo y las actividades de historia familiar ayudan a conectar generaciones en amor y propósito.", activities: [] }, education: { title: "Actividades para Jóvenes Adultos", desc: "Los jóvenes adultos se reúnen semanalmente para un breve mensaje espiritual, seguido de comida, juegos y tiempo social. Las clases de Instituto y otras discusiones del evangelio ofrecen formas significativas de aprender y crecer juntos.", activities: [] }, service: { title: "Clases de Inglés", desc: "Mejora tus habilidades en inglés a través de clases gratuitas diseñadas para todos los niveles. Nuestras clases se enfocan en conversación práctica, gramática y vocabulario útil para situaciones cotidianas. Únete a una comunidad de aprendizaje donde puedes practicar inglés mientras conoces nuevas personas.", activities: [] }, other: { title: "Otras Oportunidades", desc: "Descubre actividades y programas adicionales disponibles en nuestras ubicaciones. Contenido detallado disponible próximamente.", activities: [] }, availableActivities: "Actividades Disponibles:" },
        notifications: { fillFields: "Por favor completa todos los campos.", validEmail: "Por favor ingresa una dirección de correo electrónico válida.", thankYou: "¡Gracias por tu mensaje! Te responderemos pronto.", locationInfo: "¡Gracias! Te enviaremos información específica de la ubicación dentro de 24 horas.", enterLocation: "Por favor ingresa una ubicación para buscar.", noChurches: "No se encontraron iglesias SUD en esa área.", foundChurches: "Se encontraron {count} iglesias SUD cerca de {location}", locationNotFound: "Ubicación no encontrada. Por favor intenta con una dirección diferente.", gettingLocation: "Obteniendo Ubicación...", foundNearYou: "¡Se encontraron {count} iglesias SUD cerca de ti!", noChurchesNearYou: "No se encontraron iglesias SUD en tu área.", locationFound: "¡Ubicación encontrada! Buscando iglesias cercanas...", geolocationError: "No se pudo obtener tu ubicación. ", permissionDenied: "Por favor permite el acceso a la ubicación e intenta de nuevo.", positionUnavailable: "La información de ubicación no está disponible.", timeout: "La solicitud de ubicación expiró.", unknownError: "Ocurrió un error desconocido.", geolocationNotSupported: "La geolocalización no es compatible con este navegador.", openNow: "Abierto Ahora", closed: "Cerrado", viewAllHours: "Ver Todas las Horas", directions: "Direcciones", call: "Llamar", visitWebsite: "Visitar Sitio Web" },
        locationsList: { mainChapel: "Capilla Principal - 123 Calle de la Fe", northBuilding: "Edificio Norte - 456 Avenida de la Esperanza", eastBuilding: "Edificio Este - 789 Calle de la Caridad", southBuilding: "Edificio Sur - 321 Bulevar de la Gracia" }
    },
    en: {
        nav: { home: "Home", activities: "Activities", faith: "Our Faith", missionaries: "Missionaries", locations: "Locations", contact: "Contact" },
        hero: { title: "Welcome to Busca Cristo", subtitle: "Come unto Christ and be perfected in Him", btnActivities: "View Activities", btnLocations: "Find a Location" },
        activities: { title: "Church Activities", intro: "Discover the various activities and programs available at our church locations. Each location offers unique opportunities for spiritual growth, fellowship, and service.", worship: { title: "Church Services", desc: "Sunday worship, sacrament meetings, and special devotional services", btn: "View Activities" }, youth: { title: "Youth Activities", desc: "Activities, camps, and programs for youth ages 12-18", btn: "View Activities" }, family: { title: "Family Activities", desc: "Family home evening, activities, and programs for all ages", btn: "View Activities" }, education: { title: "Young Adult Activities", desc: "Sunday School, Institute, and other learning opportunities", btn: "View Activities" }, service: { title: "English Classes", desc: "Learn English in a supportive community environment with free classes for all levels", btn: "View Activities" }, other: { title: "Other Opportunities", desc: "Additional activities and programs available at our locations", btn: "View Activities" } },
        doctrine: { title: "Our Faith & Doctrine", intro: "Learn more about our core beliefs and teachings. Click on any topic to explore deeper understanding of our faith.", jesus: { title: "Jesus Christ", desc: "Learn about our Savior, His Atonement, and His central role in our faith and salvation" }, bom: { title: "Book of Mormon", desc: "Discover another testament of Jesus Christ and its importance in our understanding of God's plan" }, families: { title: "Eternal Families", desc: "Understand how families can be together forever through sacred temple ordinances" }, prophets: { title: "Living Prophets", desc: "Learn about modern-day revelation and how God speaks to us through His chosen servants" }, baptism: { title: "Baptism", desc: "Learn about the first principles and ordinances of the Gospel of Jesus Christ" }, salvation: { title: "Plan of Salvation", desc: "Explore God's eternal plan for His children and our purpose in this life" } },
        missionaries: { title: "Meet Our Missionaries", heading: "Sharing the Gospel of Jesus Christ", p1: "Our full-time missionaries are dedicated young men and women who have chosen to serve the Lord for 18-24 months. They come from all over the world to share the message of Jesus Christ and His restored gospel.", p2: "These missionaries are here to help you learn about our beliefs, answer your questions, and provide spiritual guidance. They offer free lessons about Jesus Christ, the Book of Mormon, and how families can be together forever.", btnMeet: "Meet with Missionaries", btnLearn: "Learn More Online", formTitle: "Meet with Missionaries", formDescription: "Fill out the form below and our missionaries will contact you to schedule a meeting.", nameLabel: "Name *", addressLabel: "Address *", learnAboutLabel: "What would you like to learn more about?", namePlaceholder: "Your name", addressPlaceholder: "Your address", learnAboutPlaceholder: "Tell us what you're interested in learning about...", submitBtn: "Submit Request", successMessage: "Thank you! We'll contact you soon." },
        locations: { title: "Find a Church Near You", useLocation: "Use My Location", or: "or", placeholder: "Enter your city, address, or postal code", findBtn: "Find Church", openMaps: "Open in Google Maps", note: "Enter a specific city rather than a large region for more accurate results." },
        contact: { title: "Contact Us", heading: "Get in Touch", p: "We'd love to hear from you and answer any questions you may have about our church or activities.", phone: "+34 93 123 4567", email: "info@buscacristo.org", address: "123 Faith Street, Barcelona, Spain", namePlaceholder: "Your Name", emailPlaceholder: "Your Email", messagePlaceholder: "Your Message", sendBtn: "Send Message" },
        footer: { about: "Busca Cristo", aboutText: "Come unto Christ and be perfected in Him through faith, repentance, baptism, and the gift of the Holy Ghost.", quickLinks: "Quick Links", resources: "Resources", follow: "Follow Us", copyright: "© 2024 Busca Cristo - The Church of Jesus Christ of Latter-day Saints. All rights reserved." },
        modal: { close: "×", activityDetails: "Activity Details", locationInfo: "Get Location-Specific Information", locationInfoDesc: "To receive detailed schedules and information for your specific location, please provide your contact information below.", firstName: "First Name *", lastName: "Last Name *", email: "Email *", phone: "Phone Number", firstNamePlaceholder: "Your first name", lastNamePlaceholder: "Your last name", emailPlaceholder: "Your email", phonePlaceholder: "Your phone number", preferredLocation: "Preferred Location *", selectLocation: "Select a location", interests: "Activities of Interest", worship: "Church Services", youth: "Youth Services", family: "Family Activities", education: "Religious Education", service: "English Classes", other: "Other Opportunities", message: "Additional Questions or Comments", messagePlaceholder: "Please let us know if you have any specific questions about activities or would like to know more about any particular program.", submitBtn: "Get Location Details", backToFaith: "Back to Our Faith" },
        breadcrumb: { home: "Home", faith: "Our Faith" },
        activitiesDetail: { worship: { title: "Church Services", desc: "Join us each week to worship, learn, and grow in faith. Our meetings include sacrament services, Sunday School, and gatherings for priesthood and Relief Society, with devotionals and testimony meetings throughout the year.", activities: [] }, youth: { title: "Youth Activities", desc: "For youth ages 12–18, we offer uplifting weekly activities, youth conferences, and summer camps that build friendships, faith, and confidence through service, learning, and fun.", activities: [] }, family: { title: "Family Activities", desc: "Families can grow closer through home evenings, service projects, and social gatherings that strengthen faith and unity. Temple trips and family history activities help connect generations in love and purpose.", activities: [] }, education: { title: "Young Adult Activities", desc: "Young adults meet weekly for a short spiritual message, followed by food, games, and social time. Institute classes and other gospel discussions offer meaningful ways to learn and grow together.", activities: [] }, service: { title: "English Classes", desc: "Improve your English skills through free classes designed for all levels. Our classes focus on practical conversation, grammar, and useful vocabulary for everyday situations. Join a learning community where you can practice English while meeting new people.", activities: [] }, other: { title: "Other Opportunities", desc: "Discover additional activities and programs available at our locations. Detailed content coming soon.", activities: [] }, availableActivities: "Available Activities:" },
        notifications: { fillFields: "Please fill in all fields.", validEmail: "Please enter a valid email address.", thankYou: "Thank you for your message! We will get back to you soon.", locationInfo: "Thank you! We will send you location-specific information within 24 hours.", enterLocation: "Please enter a location to search.", noChurches: "No LDS churches found in that area.", foundChurches: "Found {count} LDS churches near {location}", locationNotFound: "Location not found. Please try a different address.", gettingLocation: "Getting Location...", foundNearYou: "Found {count} LDS churches near you!", noChurchesNearYou: "No LDS churches found in your area.", locationFound: "Location found! Searching for nearby churches...", geolocationError: "Unable to get your location. ", permissionDenied: "Please allow location access and try again.", positionUnavailable: "Location information is unavailable.", timeout: "Location request timed out.", unknownError: "An unknown error occurred.", geolocationNotSupported: "Geolocation is not supported by this browser.", openNow: "Open Now", closed: "Closed", viewAllHours: "View All Hours", directions: "Directions", call: "Call", visitWebsite: "Visit Website" },
        locationsList: { mainChapel: "Main Chapel - 123 Faith Street", northBuilding: "North Building - 456 Hope Avenue", eastBuilding: "East Building - 789 Charity Road", southBuilding: "South Building - 321 Grace Boulevard" }
    },
    ca: {
        nav: { home: "Inici", activities: "Activitats", faith: "La Nostra Fe", missionaries: "Missioners", locations: "Ubicacions", contact: "Contacte" },
        hero: { title: "Benvingut a Busca Cristo", subtitle: "Veniu a Crist i perfeccioneu-vos en Ell", btnActivities: "Veure Activitats", btnLocations: "Trobar una Ubicació" },
        activities: { title: "Activitats de l'Església", intro: "Descobreix les diverses activitats i programes disponibles a les nostres ubicacions. Cada ubicació ofereix oportunitats úniques per al creixement espiritual, la germanor i el servei.", worship: { title: "Serveis de l'Església", desc: "Adoració diumenge, reunions de la santa cena i serveis devocionals especials", btn: "Veure Activitats" }, youth: { title: "Activitats per a Joves", desc: "Activitats, campaments i programes per a joves de 12 a 18 anys", btn: "Veure Activitats" }, family: { title: "Activitats Familiars", desc: "Nit de casa familiar, activitats i programes per a totes les edats", btn: "Veure Activitats" }, education: { title: "Activitats per a Joves Adults", desc: "Escola Diumenge, Institut i altres oportunitats d'aprenentatge", btn: "Veure Activitats" }, service: { title: "Classes d'Anglès", desc: "Aprèn anglès en un ambient comunitari de suport amb classes gratuïtes per a tots els nivells", btn: "Veure Activitats" }, temple: { title: "Adoració al Temple", desc: "Adoració al temple, història familiar i classes de preparació per al temple", btn: "Veure Activitats" } },
        doctrine: { title: "La Nostra Fe i Doctrina", intro: "Aprèn més sobre les nostres creences i ensenyaments fonamentals. Fes clic en qualsevol tema per explorar una comprensió més profunda de la nostra fe.", jesus: { title: "Jesucrist", desc: "Aprèn sobre el nostre Salvador, la Seva Expiació i el Seu paper central en la nostra fe i salvació" }, bom: { title: "Llibre de Mormó", desc: "Descobreix un altre testimoni de Jesucrist i la seva importància en la nostra comprensió del pla de Déu" }, families: { title: "Famílies Eternes", desc: "Entén com les famílies poden estar juntes per sempre a través d'ordenances sagrades del temple" }, prophets: { title: "Profetes Vius", desc: "Aprèn sobre la revelació moderna i com Déu ens parla a través dels Seus servents elegits" }, baptism: { title: "Baptisme", desc: "Aprèn sobre els primers principis i ordenances de l'Evangeli de Jesucrist" }, salvation: { title: "Pla de Salvació", desc: "Explora el pla etern de Déu per als Seus fills i el nostre propòsit en aquesta vida" } },
        missionaries: { title: "Coneix els Nostres Missioners", heading: "Compartint l'Evangeli de Jesucrist", p1: "Els nostres missioners de temps complet són joves dedicats que han triat servir el Senyor durant 18-24 mesos. Vénen de tot el món per compartir el missatge de Jesucrist i el Seu evangeli restaurat.", p2: "Aquests missioners estan aquí per ajudar-te a aprendre sobre les nostres creences, respondre les teves preguntes i brindar orientació espiritual. Oferixen lliçons gratuïtes sobre Jesucrist, el Llibre de Mormó i com les famílies poden estar juntes per sempre.", btnMeet: "Reunir-se amb Missioners", btnLearn: "Aprèn Més en Línia", formTitle: "Reunir-se amb Missioners", formDescription: "Completa el formulari a continuació i els nostres missioners es posaran en contacte amb tu per programar una reunió.", nameLabel: "Nom *", addressLabel: "Adreça *", learnAboutLabel: "Sobre què t'agradaria aprendre més?", namePlaceholder: "El teu nom", addressPlaceholder: "La teva adreça", learnAboutPlaceholder: "Explica'ns què t'interessa aprendre...", submitBtn: "Enviar Sol·licitud", successMessage: "Gràcies! Ens posarem en contacte amb tu aviat." },
        locations: { title: "Troba una Església a Prop de Tu", useLocation: "Utilitzar la Meva Ubicació", or: "o", placeholder: "Introdueix la teva ciutat, adreça o codi postal", findBtn: "Buscar Església", openMaps: "Obrir a Google Maps", note: "Introdueix una ciutat específica en lloc d'una regió gran per obtenir resultats més precisos." },
        contact: { title: "Contacta'ns", heading: "Posar-se en Contacte", p: "Ens encantaria saber de tu i respondre qualsevol pregunta que puguis tenir sobre la nostra església o activitats.", phone: "+34 93 123 4567", email: "info@buscacristo.org", address: "123 Carrer de la Fe, Barcelona, Espanya", namePlaceholder: "El Teu Nom", emailPlaceholder: "El Teu Correu", messagePlaceholder: "El Teu Missatge", sendBtn: "Enviar Missatge" },
        footer: { about: "Busca Cristo", aboutText: "Veniu a Crist i perfeccioneu-vos en Ell mitjançant la fe, el penediment, el baptisme i el do de l'Esperit Sant.", quickLinks: "Enllaços Ràpids", resources: "Recursos", follow: "Segueix-nos", copyright: "© 2024 Busca Cristo - L'Església de Jesucrist dels Sants dels Últims Dies. Tots els drets reservats." },
        modal: { close: "×", activityDetails: "Detalls de l'Activitat", locationInfo: "Obtenir Informació Específica de la Ubicació", locationInfoDesc: "Per rebre horaris detallats i informació per a la teva ubicació específica, si us plau proporciona la teva informació de contacte a continuació.", firstName: "Nom *", lastName: "Cognom *", email: "Correu Electrònic *", phone: "Número de Telèfon", firstNamePlaceholder: "El teu nom", lastNamePlaceholder: "El teu cognom", emailPlaceholder: "El teu correu", phonePlaceholder: "El teu telèfon", preferredLocation: "Ubicació Preferida *", selectLocation: "Selecciona una ubicació", interests: "Activitats d'Interès", worship: "Serveis de l'Església", youth: "Serveis per a Joves", family: "Activitats Familiars", education: "Educació Religiosa", service: "Classes d'Anglès", temple: "Activitats del Temple", message: "Preguntes o Comentaris Addicionals", messagePlaceholder: "Si us plau, fes-nos-ho saber si tens preguntes específiques sobre activitats o t'agradaria saber més sobre algun programa en particular.", submitBtn: "Obtenir Detalls d'Ubicació", backToFaith: "Tornar a La Nostra Fe" },
        breadcrumb: { home: "Inici", faith: "La Nostra Fe" },
        activitiesDetail: { worship: { title: "Serveis de l'Església", desc: "Uneix-te a nosaltres cada setmana per adorar, aprendre i créixer en la fe. Les nostres reunions inclouen serveis de la santa cena, Escola Diumenge i reunions de sacerdoci i Societat de Socors, amb devocionals i reunions de testimonis durant tot l'any.", activities: [] }, youth: { title: "Activitats per a Joves", desc: "Per a joves de 12 a 18 anys, oferim activitats setmanals edificants, conferències de joves i campaments d'estiu que construeixen amistats, fe i confiança a través del servei, l'aprenentatge i la diversió.", activities: [] }, family: { title: "Activitats Familiars", desc: "Les famílies poden apropar-se més a través de les nits de casa familiar, projectes de servei i reunions socials que enforteixen la fe i la unitat. Els viatges al temple i les activitats d'història familiar ajuden a connectar generacions en amor i propòsit.", activities: [] }, education: { title: "Activitats per a Joves Adults", desc: "Els joves adults es reuneixen setmanalment per a un breu missatge espiritual, seguit de menjar, jocs i temps social. Les classes d'Institut i altres discussions de l'evangeli ofereixen formes significatives d'aprendre i créixer junts.", activities: [] }, service: { title: "Classes d'Anglès", desc: "Millora les teves habilitats en anglès a través de classes gratuïtes dissenyades per a tots els nivells. Les nostres classes se centren en conversa pràctica, gramàtica i vocabulari útil per a situacions quotidianes. Uneix-te a una comunitat d'aprenentatge on pots practicar anglès mentre coneixes noves persones.", activities: [] }, temple: { title: "Adoració al Temple", desc: "Troba pau i propòsit a través de l'adoració i el servei al temple. Participa en sessions del temple, classes de preparació i treball d'història familiar que enforteixen la fe i aporten goig espiritual.", activities: [] }, availableActivities: "Activitats Disponibles:" },
        notifications: { fillFields: "Si us plau completa tots els camps.", validEmail: "Si us plau introdueix una adreça de correu electrònic vàlida.", thankYou: "Gràcies pel teu missatge! Et respondrem aviat.", locationInfo: "Gràcies! T'enviarem informació específica de la ubicació dins de 24 hores.", enterLocation: "Si us plau introdueix una ubicació per buscar.", noChurches: "No s'han trobat esglésies SUD en aquesta àrea.", foundChurches: "S'han trobat {count} esglésies SUD a prop de {location}", locationNotFound: "Ubicació no trobada. Si us plau intenta amb una adreça diferent.", gettingLocation: "Obtenint Ubicació...", foundNearYou: "S'han trobat {count} esglésies SUD a prop de tu!", noChurchesNearYou: "No s'han trobat esglésies SUD a la teva àrea.", locationFound: "Ubicació trobada! Buscant esglésies properes...", geolocationError: "No s'ha pogut obtenir la teva ubicació. ", permissionDenied: "Si us plau permet l'accés a la ubicació i intenta de nou.", positionUnavailable: "La informació d'ubicació no està disponible.", timeout: "La sol·licitud d'ubicació ha expirat.", unknownError: "S'ha produït un error desconegut.", geolocationNotSupported: "La geolocalització no és compatible amb aquest navegador.", openNow: "Obert Ara", closed: "Tancat", viewAllHours: "Veure Totes les Hores", directions: "Direccions", call: "Trucar", visitWebsite: "Visitar Lloc Web" },
        locationsList: { mainChapel: "Capella Principal - 123 Carrer de la Fe", northBuilding: "Edifici Nord - 456 Avinguda de l'Esperança", eastBuilding: "Edifici Est - 789 Carrer de la Caritat", southBuilding: "Edifici Sud - 321 Bulevard de la Gràcia" }
    },
    fr: {
        nav: { home: "Accueil", activities: "Activités", faith: "Notre Foi", missionaries: "Missionnaires", locations: "Emplacements", contact: "Contact" },
        hero: { title: "Bienvenue à Busca Cristo", subtitle: "Venez au Christ et soyez rendus parfaits en Lui", btnActivities: "Voir les Activités", btnLocations: "Trouver un Emplacement" },
        activities: { title: "Activités de l'Église", intro: "Découvrez les diverses activités et programmes disponibles dans nos emplacements. Chaque emplacement offre des opportunités uniques pour la croissance spirituelle, la fraternité et le service.", worship: { title: "Services de l'Église", desc: "Culte du dimanche, réunions de la sainte cène et services dévotionnels spéciaux", btn: "Voir les Activités" }, youth: { title: "Activités pour les Jeunes", desc: "Activités, camps et programmes pour les jeunes de 12 à 18 ans", btn: "Voir les Activités" }, family: { title: "Activités Familiales", desc: "Soirée familiale, activités et programmes pour tous les âges", btn: "Voir les Activités" }, education: { title: "Activités pour les Jeunes Adultes", desc: "École du Dimanche, Institut et autres opportunités d'apprentissage", btn: "Voir les Activités" }, service: { title: "Cours d'Anglais", desc: "Apprenez l'anglais dans un environnement communautaire bienveillant avec des cours gratuits pour tous les niveaux", btn: "Voir les Activités" }, temple: { title: "Culte au Temple", desc: "Culte au temple, histoire familiale et classes de préparation au temple", btn: "Voir les Activités" } },
        doctrine: { title: "Notre Foi et Doctrine", intro: "Apprenez-en plus sur nos croyances et enseignements fondamentaux. Cliquez sur n'importe quel sujet pour explorer une compréhension plus profonde de notre foi.", jesus: { title: "Jésus-Christ", desc: "Apprenez-en plus sur notre Sauveur, Son Expiation et Son rôle central dans notre foi et notre salut" }, bom: { title: "Livre de Mormon", desc: "Découvrez un autre témoignage de Jésus-Christ et son importance dans notre compréhension du plan de Dieu" }, families: { title: "Familles Éternelles", desc: "Comprenez comment les familles peuvent être ensemble pour toujours à travers les ordonnances sacrées du temple" }, prophets: { title: "Prophètes Vivants", desc: "Apprenez-en plus sur la révélation moderne et comment Dieu nous parle à travers Ses serviteurs choisis" }, baptism: { title: "Baptême", desc: "Apprenez-en plus sur les premiers principes et ordonnances de l'Évangile de Jésus-Christ" }, salvation: { title: "Plan de Salut", desc: "Explorez le plan éternel de Dieu pour Ses enfants et notre but dans cette vie" } },
        missionaries: { title: "Rencontrez nos Missionnaires", heading: "Partager l'Évangile de Jésus-Christ", p1: "Nos missionnaires à plein temps sont de jeunes hommes et femmes dévoués qui ont choisi de servir le Seigneur pendant 18-24 mois. Ils viennent du monde entier pour partager le message de Jésus-Christ et Son évangile restauré.", p2: "Ces missionnaires sont là pour vous aider à apprendre nos croyances, répondre à vos questions et fournir des conseils spirituels. Ils offrent des leçons gratuites sur Jésus-Christ, le Livre de Mormon et comment les familles peuvent être ensemble pour toujours.", btnMeet: "Rencontrer les Missionnaires", btnLearn: "En Savoir Plus en Ligne", formTitle: "Rencontrer les Missionnaires", formDescription: "Remplissez le formulaire ci-dessous et nos missionnaires vous contacteront pour planifier une réunion.", nameLabel: "Nom *", addressLabel: "Adresse *", learnAboutLabel: "Sur quoi aimeriez-vous en savoir plus?", namePlaceholder: "Votre nom", addressPlaceholder: "Votre adresse", learnAboutPlaceholder: "Dites-nous ce qui vous intéresse d'apprendre...", submitBtn: "Soumettre la Demande", successMessage: "Merci! Nous vous contacterons bientôt." },
        locations: { title: "Trouvez une Église Près de Vous", useLocation: "Utiliser Ma Position", or: "ou", placeholder: "Entrez votre ville, adresse ou code postal", findBtn: "Trouver une Église", openMaps: "Ouvrir dans Google Maps", note: "Entrez une ville spécifique plutôt qu'une grande région pour des résultats plus précis." },
        contact: { title: "Contactez-nous", heading: "Entrer en Contact", p: "Nous aimerions avoir de vos nouvelles et répondre à toutes vos questions sur notre église ou nos activités.", phone: "+34 93 123 4567", email: "info@buscacristo.org", address: "123 Rue de la Foi, Barcelone, Espagne", namePlaceholder: "Votre Nom", emailPlaceholder: "Votre Email", messagePlaceholder: "Votre Message", sendBtn: "Envoyer le Message" },
        footer: { about: "Busca Cristo", aboutText: "Venez au Christ et soyez rendus parfaits en Lui par la foi, le repentir, le baptême et le don du Saint-Esprit.", quickLinks: "Liens Rapides", resources: "Ressources", follow: "Suivez-nous", copyright: "© 2024 Busca Cristo - L'Église de Jésus-Christ des Saints des Derniers Jours. Tous droits réservés." },
        modal: { close: "×", activityDetails: "Détails de l'Activité", locationInfo: "Obtenir des Informations Spécifiques à l'Emplacement", locationInfoDesc: "Pour recevoir des horaires détaillés et des informations pour votre emplacement spécifique, veuillez fournir vos informations de contact ci-dessous.", firstName: "Prénom *", lastName: "Nom *", email: "Email *", phone: "Numéro de Téléphone", firstNamePlaceholder: "Votre prénom", lastNamePlaceholder: "Votre nom", emailPlaceholder: "Votre email", phonePlaceholder: "Votre numéro de téléphone", preferredLocation: "Emplacement Préféré *", selectLocation: "Sélectionnez un emplacement", interests: "Activités d'Intérêt", worship: "Services de l'Église", youth: "Services pour les Jeunes", family: "Activités Familiales", education: "Éducation Religieuse", service: "Cours d'Anglais", temple: "Activités du Temple", message: "Questions ou Commentaires Supplémentaires", messagePlaceholder: "Veuillez nous faire savoir si vous avez des questions spécifiques sur les activités ou si vous souhaitez en savoir plus sur un programme particulier.", submitBtn: "Obtenir les Détails de l'Emplacement", backToFaith: "Retour à Notre Foi" },
        breadcrumb: { home: "Accueil", faith: "Notre Foi" },
        activitiesDetail: { worship: { title: "Services de l'Église", desc: "Rejoignez-nous chaque semaine pour adorer, apprendre et grandir dans la foi. Nos réunions comprennent les services de la sainte cène, l'École du Dimanche et les réunions de prêtrise et de Société de Secours, avec des dévotionnels et des réunions de témoignage tout au long de l'année.", activities: [] }, youth: { title: "Activités pour les Jeunes", desc: "Pour les jeunes de 12 à 18 ans, nous offrons des activités hebdomadaires édificantes, des conférences de jeunes et des camps d'été qui construisent des amitiés, la foi et la confiance grâce au service, à l'apprentissage et au plaisir.", activities: [] }, family: { title: "Activités Familiales", desc: "Les familles peuvent se rapprocher grâce aux soirées familiales, aux projets de service et aux rassemblements sociaux qui renforcent la foi et l'unité. Les voyages au temple et les activités d'histoire familiale aident à connecter les générations dans l'amour et le but.", activities: [] }, education: { title: "Activités pour les Jeunes Adultes", desc: "Les jeunes adultes se réunissent chaque semaine pour un bref message spirituel, suivi de nourriture, de jeux et de temps social. Les classes d'Institut et d'autres discussions de l'évangile offrent des moyens significatifs d'apprendre et de grandir ensemble.", activities: [] }, service: { title: "Cours d'Anglais", desc: "Améliorez vos compétences en anglais grâce à des cours gratuits conçus pour tous les niveaux. Nos cours se concentrent sur la conversation pratique, la grammaire et le vocabulaire utile pour les situations quotidiennes. Rejoignez une communauté d'apprentissage où vous pouvez pratiquer l'anglais tout en rencontrant de nouvelles personnes.", activities: [] }, temple: { title: "Culte au Temple", desc: "Trouvez la paix et le but grâce à l'adoration et au service au temple. Participez aux sessions du temple, aux classes de préparation et au travail d'histoire familiale qui renforcent la foi et apportent la joie spirituelle.", activities: [] }, availableActivities: "Activités Disponibles:" },
        notifications: { fillFields: "Veuillez remplir tous les champs.", validEmail: "Veuillez entrer une adresse email valide.", thankYou: "Merci pour votre message! Nous vous répondrons bientôt.", locationInfo: "Merci! Nous vous enverrons des informations spécifiques à l'emplacement dans les 24 heures.", enterLocation: "Veuillez entrer un emplacement à rechercher.", noChurches: "Aucune église SUD trouvée dans cette zone.", foundChurches: "Trouvé {count} églises SUD près de {location}", locationNotFound: "Emplacement non trouvé. Veuillez essayer une adresse différente.", gettingLocation: "Obtention de la Position...", foundNearYou: "Trouvé {count} églises SUD près de vous!", noChurchesNearYou: "Aucune église SUD trouvée dans votre zone.", locationFound: "Emplacement trouvé! Recherche d'églises à proximité...", geolocationError: "Impossible d'obtenir votre position. ", permissionDenied: "Veuillez autoriser l'accès à la position et réessayer.", positionUnavailable: "Les informations de position ne sont pas disponibles.", timeout: "La demande de position a expiré.", unknownError: "Une erreur inconnue s'est produite.", geolocationNotSupported: "La géolocalisation n'est pas prise en charge par ce navigateur.", openNow: "Ouvert Maintenant", closed: "Fermé", viewAllHours: "Voir Toutes les Heures", directions: "Itinéraires", call: "Appeler", visitWebsite: "Visiter le Site Web" },
        locationsList: { mainChapel: "Chapelle Principale - 123 Rue de la Foi", northBuilding: "Bâtiment Nord - 456 Avenue de l'Espérance", eastBuilding: "Bâtiment Est - 789 Rue de la Charité", southBuilding: "Bâtiment Sud - 321 Boulevard de la Grâce" }
    }
};

// Doctrine page translations
translations.es.doctrinePages = {
    jesusChrist: {
        title: "Jesucristo",
        subtitle: "Nuestro Salvador, Redentor y la figura central de nuestra fe",
        backToFaith: "Volver a Nuestra Fe",
        whoIs: { title: "¿Quién es Jesucristo?", p1: "Jesucristo es el Hijo de Dios, el Salvador y Redentor del mundo. Él es la figura central de nuestra fe y el fundamento de nuestra esperanza. A través de Su Expiación infinita, toda la humanidad puede ser salva mediante la obediencia a las leyes y ordenanzas del Evangelio.", p2: "Creemos que Jesucristo es el Hijo literal de Dios, nacido de María en Belén. Vivió una vida perfecta y sin pecado, mostrándonos el camino para vivir y servir a otros. Sus enseñanzas, milagros y ejemplo proporcionan el patrón para nuestras vidas." },
        atonement: { title: "La Expiación de Jesucristo", p1: "La Expiación de Jesucristo es la doctrina central de nuestra fe. A través de Su sufrimiento en Getsemaní y Su muerte en la cruz, Jesucristo tomó sobre Sí mismo los pecados, dolores y aflicciones de toda la humanidad. Este sacrificio infinito hace posible que seamos perdonados de nuestros pecados y regresemos a vivir con nuestro Padre Celestial.", scripture: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.", reference: "Juan 3:16", p2: "La Expiación no solo proporciona el perdón de nuestros pecados, sino que también nos da fuerza para superar nuestras debilidades y desafíos. A través de Su gracia, podemos convertirnos en mejores personas y acercarnos más a Dios." },
        following: { title: "Siguiendo el Ejemplo de Cristo", p1: "Como seguidores de Jesucristo, nos esforzamos por vivir como Él vivió. Esto significa amar a Dios con todo nuestro corazón, mente, fuerza y poder, y amar a nuestro prójimo como a nosotros mismos. Buscamos servir a otros, mostrar compasión y vivir con integridad y fe.", p2: "Cristo nos enseñó a ser humildes, perdonadores y caritativos. Nos mostró cómo orar, cómo tratar a otros con bondad y cómo confiar en el plan de nuestro Padre Celestial. Al seguir Su ejemplo, podemos encontrar paz, gozo y propósito en nuestras vidas." },
        relationship: { title: "Nuestra Relación con Cristo", p1: "Jesucristo no es solo una figura histórica para nosotros—Él es nuestro Salvador viviente. Creemos que Él nos conoce personalmente a cada uno de nosotros y nos ama incondicionalmente. A través de la oración, el estudio de las escrituras y seguir Sus enseñanzas, podemos desarrollar una relación personal con Él.", p2: "A medida que venimos a Cristo, encontramos sanación, esperanza y dirección para nuestras vidas. Él es nuestro abogado con el Padre y nuestra fuente de fortaleza en tiempos de prueba. A través de Su Expiación, podemos ser transformados y llegar a ser más como Él." },
        related: "Temas Relacionados"
    },
    bookOfMormon: {
        title: "Libro de Mormón",
        subtitle: "Otro Testamento de Jesucristo",
        backToFaith: "Volver a Nuestra Fe",
        whatIs: { title: "¿Qué es el Libro de Mormón?", p1: "El Libro de Mormón es otro testamento de Jesucristo, confirmando las verdades que se encuentran en la Biblia. Es un registro sagrado de civilizaciones americanas antiguas y contiene la plenitud del evangelio sempiterno. El libro fue escrito por profetas antiguos que vivieron en el continente americano desde aproximadamente 600 a.C. hasta 421 d.C.", p2: "El Libro de Mormón testifica de Jesucristo y Su misión divina. Enseña los mismos principios de fe, arrepentimiento, bautismo y el don del Espíritu Santo que se encuentran en la Biblia. Juntos, la Biblia y el Libro de Mormón proporcionan una comprensión más completa del plan de Dios para Sus hijos." },
        comingForth: { title: "La Venida del Libro de Mormón", p1: "El Libro de Mormón fue traducido por José Smith mediante el don y el poder de Dios. Los registros originales fueron escritos en planchas de oro y estuvieron enterrados en la tierra por más de 1,400 años. En 1823, el ángel Moroni se apareció a José Smith y le habló sobre estos registros sagrados.", scripture: "Y traerá un nuevo registro, y en él estará el mismo evangelio que él les ha declarado en la Biblia; y no habrá más de dos naciones.", reference: "Ezequiel 37:16-17", p2: "Después de cuatro años de preparación, José Smith recibió las planchas de oro y las tradujo por el poder de Dios. El Libro de Mormón se publicó por primera vez en 1830 y desde entonces ha sido traducido a más de 100 idiomas." },
        teachings: { title: "Enseñanzas Clave del Libro de Mormón", p1: "El Libro de Mormón contiene muchas enseñanzas importantes sobre Jesucristo, incluyendo Su nacimiento, ministerio, muerte y resurrección. Enseña sobre la importancia de la fe, el arrepentimiento, el bautismo y recibir el don del Espíritu Santo. El libro también enfatiza la importancia de las familias, el servicio a otros y seguir los mandamientos de Dios.", p2: "Una de las enseñanzas más poderosas en el Libro de Mormón es sobre la Expiación de Jesucristo. El libro enseña que a través del sacrificio de Cristo, toda la humanidad puede ser salva y regresar a vivir con Dios. También enseña sobre la importancia de la revelación personal y cómo podemos recibir guía de Dios en nuestra vida diaria." },
        promise: { title: "La Promesa del Libro de Mormón", p1: "El Libro de Mormón contiene una promesa de que cualquiera que lo lea con corazón sincero y pregunte a Dios con fe recibirá un testimonio de su veracidad. Esta promesa se encuentra en Moroni 10:3-5, donde se nos invita a leer, meditar y orar sobre el libro.", scripture: "Y cuando recibáis estas cosas, quisiera exhortaros a que preguntéis a Dios, el Padre Eterno, en el nombre de Cristo, si estas cosas no son verdaderas; y si pedís con corazón sincero, con verdadera intención, teniendo fe en Cristo, él os manifestará la verdad de ellas por el poder del Espíritu Santo.", reference: "Moroni 10:4", p2: "Esta promesa se aplica a todos los que leen el Libro de Mormón. A través de la oración y el estudio, podemos recibir un testimonio personal de que el libro es verdadero y que contiene la palabra de Dios." },
        study: { title: "Cómo Estudiar el Libro de Mormón", p1: "El Libro de Mormón está destinado a ser estudiado con oración y regularmente. Animamos a todos a leerlo diariamente, meditar en sus enseñanzas y aplicar sus principios en sus vidas. El libro puede leerse individualmente o en familia, y hay muchos recursos disponibles para ayudar a comprender sus enseñanzas.", p2: "Mientras estudias el Libro de Mormón, busca principios que se apliquen a tu vida. Presta atención a los ejemplos de fe, valentía y obediencia mostrados por las personas en el libro. Lo más importante, ora por entendimiento y guía mientras lees." },
        related: "Temas Relacionados"
    },
    eternalFamilies: {
        title: "Familias Eternas",
        subtitle: "Las Familias Pueden Estar Juntas para Siempre",
        backToFaith: "Volver a Nuestra Fe",
        divineNature: { title: "La Naturaleza Divina de las Familias", p1: "Las familias son centrales en el plan de Dios para Sus hijos. Creemos que las familias pueden estar juntas para siempre a través de ordenanzas sagradas del templo. La familia es la unidad fundamental de la sociedad y la organización más importante en el tiempo y la eternidad. Dios estableció las familias para proporcionar amor, apoyo y guía para Sus hijos.", p2: "La familia es donde aprendemos a amar, servir y cuidar a otros. Es donde desarrollamos nuestro carácter, valores y fe. A través de las relaciones familiares, experimentamos gozo, crecimiento y las bendiciones del amor de Dios. La familia proporciona un refugio seguro donde podemos aprender, crecer y llegar a ser las personas que Dios quiere que seamos." },
        templeMarriage: { title: "Matrimonio en el Templo y Familias Eternas", p1: "En los templos, las parejas dignas pueden ser selladas juntas por el tiempo y toda la eternidad. Esta ordenanza sagrada, realizada por la autoridad apropiada del sacerdocio, une a las familias más allá de la muerte. Cuando una pareja es sellada en el templo, su matrimonio no es solo para esta vida sino para la eternidad.", scripture: "Y a ti te daré las llaves del reino de los cielos; y todo lo que ates en la tierra será atado en los cielos; y todo lo que desates en la tierra será desatado en los cielos.", reference: "Mateo 16:19", p2: "Los niños nacidos de padres que han sido sellados en el templo están automáticamente sellados a sus padres por la eternidad. Esto significa que las familias pueden estar juntas para siempre, no solo hasta que la muerte las separe. Esta es una de las mayores bendiciones del evangelio de Jesucristo." },
        familyHistory: { title: "Historia Familiar y Obra del Templo", p1: "Creemos que todos los hijos de Dios, tanto vivos como muertos, deben tener la oportunidad de recibir las bendiciones del evangelio. A través de la investigación de historia familiar y la obra del templo, podemos ayudar a nuestros antepasados fallecidos a recibir las ordenanzas de salvación, incluyendo el bautismo, la confirmación y el sellamiento del templo.", p2: "La obra de historia familiar nos conecta con nuestros antepasados y nos ayuda a entender nuestro patrimonio. Fortalece a nuestras familias y nos acerca más a Dios. Cuando realizamos ordenanzas del templo para nuestros antepasados, los estamos ayudando a progresar en su viaje eterno y fortaleciendo los lazos de nuestra familia eterna." },
        strengthening: { title: "Fortaleciendo las Familias Hoy", p1: "Mientras que las familias eternas son una bendición futura, podemos comenzar a fortalecer nuestras familias hoy. Esto incluye la oración familiar regular, el estudio de las escrituras y la noche de hogar familiar. También debemos pasar tiempo de calidad juntos, apoyarnos mutuamente y trabajar juntos para superar desafíos.", p2: "Las familias fuertes se construyen sobre principios de amor, respeto, perdón y servicio. Los padres deben enseñar el evangelio a sus hijos y ayudarlos a desarrollar fe en Jesucristo. Los hijos deben honrar y obedecer a sus padres. Cuando las familias trabajan juntas y se apoyan mutuamente, se vuelven más fuertes y más unidas." },
        promise: { title: "La Promesa de las Familias Eternas", p1: "La promesa de las familias eternas nos da esperanza y consuelo en tiempos de pérdida y separación. Sabemos que la muerte no es el fin de nuestras relaciones con nuestros seres queridos. A través de la Expiación de Jesucristo y el poder del sacerdocio, las familias pueden ser reunidas y vivir juntas para siempre en la presencia de Dios.", scripture: "Y si acontece que trabajáis todos vuestros días proclamando el arrepentimiento a este pueblo y traéis, aunque sea una sola alma a mí, ¡cuán grande será vuestro gozo con ella en el reino de mi Padre!", reference: "Doctrina y Convenios 18:15", p2: "Esta promesa nos motiva a vivir rectamente y a trabajar para ser dignos de la vida eterna. Nos anima a fortalecer nuestras relaciones familiares y a ayudar a otros a venir a Cristo. La familia no es solo un arreglo temporal sino una institución eterna que continuará para siempre." },
        related: "Temas Relacionados"
    },
    livingProphets: {
        title: "Profetas Vivientes",
        subtitle: "Dios Habla a Través de Sus Siervos Elegidos",
        backToFaith: "Volver a Nuestra Fe",
        whatIs: { title: "¿Qué es un Profeta?", p1: "Un profeta es un hombre llamado por Dios para ser Su portavoz en la tierra. Los profetas reciben revelación de Dios y enseñan Su voluntad al pueblo. Son elegidos por Dios para dirigir Su iglesia y guiar a Sus hijos en la rectitud. A lo largo de la historia, Dios ha llamado profetas para enseñar Su evangelio y advertir a Su pueblo.", p2: "Los profetas no son hombres perfectos, pero son llamados por Dios y sostenidos por el pueblo. Reciben inspiración y revelación para guiar la iglesia y ayudar a los hijos de Dios a navegar los desafíos de su tiempo. Hablan por Dios y proporcionan dirección para nuestras vidas." },
        modernRevelation: { title: "Revelación Moderna", p1: "Creemos que Dios continúa hablando a Sus hijos hoy a través de profetas vivientes. Así como Dios habló a Moisés, Isaías y otros profetas antiguos, Él habla a Sus profetas hoy. Esta revelación moderna nos ayuda a entender la voluntad de Dios para nuestro tiempo y proporciona guía para los desafíos que enfrentamos.", scripture: "Porque no hará nada Jehová el Señor, sin que revele su secreto a sus siervos los profetas.", reference: "Amós 3:7", p2: "La revelación moderna viene a través del Presidente de La Iglesia de Jesucristo de los Santos de los Últimos Días, quien sirve como profeta, vidente y revelador para todo el mundo. Esta revelación se da en discursos de conferencia general, declaraciones oficiales y otras comunicaciones inspiradas." },
        firstPresidency: { title: "La Primera Presidencia y el Quórum de los Doce", p1: "La Primera Presidencia consiste en el Presidente de la Iglesia y sus dos consejeros. El Quórum de los Doce Apóstoles son testigos especiales de Jesucristo y sirven bajo la dirección de la Primera Presidencia. Juntos, estos quince hombres forman el cuerpo gobernante de la iglesia y reciben revelación para todo el mundo.", p2: "Estos hombres son llamados por Dios y sostenidos por los miembros de la iglesia. Viajan por todo el mundo para enseñar, testificar y ministrar a los hijos de Dios. Proporcionan guía sobre asuntos de doctrina, política y conducta personal. Sus enseñanzas nos ayudan a entender la voluntad de Dios y vivir de acuerdo con Sus mandamientos." },
        generalConference: { title: "Conferencia General", p1: "Dos veces al año, la iglesia celebra conferencia general, donde el profeta y otros líderes de la iglesia hablan a todo el mundo. Estas conferencias se transmiten en todo el mundo y proporcionan una oportunidad para que todos los miembros escuchen la palabra de Dios a través de Sus siervos elegidos. Los mensajes dados en la conferencia general se consideran escritura y proporcionan guía para nuestras vidas.", p2: "Los discursos de la conferencia general cubren una amplia gama de temas, incluyendo fe, arrepentimiento, servicio, familia y desafíos actuales que enfrenta el mundo. Estos mensajes proporcionan consuelo, guía y dirección para los miembros de la iglesia y cualquiera que elija escuchar. Nos ayudan a entender cómo aplicar los principios del evangelio en nuestra vida diaria." },
        following: { title: "Siguiendo al Profeta", p1: "Se nos anima a seguir el consejo de los profetas vivientes. Sus enseñanzas nos ayudan a permanecer en el camino que lleva a la vida eterna. Cuando seguimos Su guía, somos bendecidos con paz, protección y crecimiento espiritual. Las palabras del profeta no son solo sugerencias sino guía inspirada de Dios.", scripture: "Ya sea por mi propia voz o por la voz de mis siervos, es lo mismo.", reference: "Doctrina y Convenios 1:38", p2: "Seguir al profeta requiere fe y obediencia. Puede que no siempre entendamos por qué se da cierto consejo, pero podemos confiar en que viene de Dios y es para nuestro beneficio. A medida que seguimos la guía del profeta, seremos bendecidos y protegidos de los males del mundo." },
        related: "Temas Relacionados"
    },
    baptism: {
        title: "Bautismo",
        subtitle: "Los Primeros Principios y Ordenanzas del Evangelio",
        backToFaith: "Volver a Nuestra Fe",
        faith: { title: "Fe en Jesucristo", p1: "La fe es el primer principio del evangelio. Es una esperanza en cosas que no se ven, pero que son verdaderas. La fe en Jesucristo significa confiar en Él, creer en Sus enseñanzas y seguir Su ejemplo. Cuando tenemos fe en Cristo, Lo aceptamos como nuestro Salvador y Redentor y creemos que a través de Su Expiación, podemos ser perdonados de nuestros pecados y regresar a vivir con Dios.", scripture: "Y ahora, como dije concerniente a la fe—la fe no es tener un conocimiento perfecto de las cosas; por tanto, si tenéis fe, esperáis en cosas que no se ven, que son verdaderas.", reference: "Alma 32:21", p2: "La fe nos lleva a actuar. Cuando tenemos fe en Jesucristo, estamos dispuestos a guardar Sus mandamientos, arrepentirnos de nuestros pecados y seguir Sus enseñanzas. La fe es como una semilla—cuando la plantamos y la nutrimos, crece y produce buenos frutos en nuestras vidas." },
        repentance: { title: "Arrepentimiento", p1: "El arrepentimiento es el segundo principio del evangelio. Es el proceso de cambiar nuestros pensamientos, creencias y comportamientos para alinearlos con la voluntad de Dios. A través del arrepentimiento, nos alejamos del pecado y nos volvemos hacia Dios. El arrepentimiento implica reconocer nuestros errores, sentir pesar por ellos, confesarlos a Dios, hacer restitución cuando sea posible y comprometernos a cambiar.", scripture: "Por esto sabréis si un hombre se arrepiente de sus pecados—he aquí, los confesará y los abandonará.", reference: "Doctrina y Convenios 58:43", p2: "El arrepentimiento es posible gracias a la Expiación de Jesucristo. Cuando nos arrepentimos, podemos ser perdonados de nuestros pecados y recibir paz y gozo. El arrepentimiento no es un evento único sino un proceso continuo a lo largo de nuestras vidas mientras nos esforzamos por llegar a ser más como Cristo." },
        baptism: { title: "Bautismo", p1: "El bautismo es la primera ordenanza del evangelio y es esencial para la salvación. Se realiza por inmersión en agua por alguien que tiene la autoridad apropiada del sacerdocio. El bautismo representa la muerte, sepultura y resurrección de Jesucristo y simboliza nuestro compromiso de seguirle. Cuando somos bautizados, hacemos un convenio con Dios de tomar sobre nosotros el nombre de Jesucristo, recordarle siempre y guardar Sus mandamientos.", scripture: "Y ahora, si el Cordero de Dios, siendo santo, tiene necesidad de ser bautizado por agua para cumplir toda justicia, ¡oh entonces, cuánto más necesidad tenemos nosotros, siendo impuros, de ser bautizados, sí, aun por agua!", reference: "2 Nefi 31:5", p2: "El bautismo es la puerta de entrada al sendero que conduce a la vida eterna. A través del bautismo, somos limpiados de nuestros pecados y nos convertimos en miembros de la iglesia de Cristo. Somos bautizados a la edad de responsabilidad (ocho años) o cuando tenemos la edad suficiente para entender y hacer este importante convenio con Dios." },
        holyghost: { title: "El Don del Espíritu Santo", p1: "Después del bautismo, recibimos el don del Espíritu Santo mediante la imposición de manos por aquellos con autoridad del sacerdocio. El Espíritu Santo es el tercer miembro de la Trinidad y sirve como un compañero constante, guía y consolador. El don del Espíritu Santo es diferente de la influencia del Espíritu Santo—es el derecho de tener al Espíritu Santo como un compañero constante, siempre que permanezcamos dignos.", scripture: "Y por el poder del Espíritu Santo podréis conocer la verdad de todas las cosas.", reference: "Moroni 10:5", p2: "El Espíritu Santo nos ayuda de muchas maneras: Él testifica de la verdad, nos advierte del peligro, nos consuela en tiempos de necesidad, nos guía en la toma de decisiones y nos ayuda a entender las escrituras. Cuando vivimos rectamente y guardamos los mandamientos, podemos tener la compañía constante del Espíritu Santo, que trae paz, gozo y fortaleza espiritual." },
        endure: { title: "Perseverar hasta el Fin", p1: "Perseverar hasta el fin significa permanecer fieles a los convenios que hacemos a lo largo de nuestras vidas. Significa continuar teniendo fe en Jesucristo, arrepintiéndonos diariamente, guardando los mandamientos y sirviendo a otros. Perseverar hasta el fin no se trata solo de sobrevivir—se trata de crecer, aprender y llegar a ser más como nuestro Salvador.", scripture: "Mírame en todo pensamiento; no dudes, no temas. He aquí las heridas que traspasaron mi costado, y también las impresiones de los clavos en mis manos y pies; sed fieles, guardad mis mandamientos, y heredaréis el reino de los cielos.", reference: "Doctrina y Convenios 6:36-37", p2: "El evangelio de Jesucristo es una forma de vida, no solo un evento único. A medida que perseveramos hasta el fin, continuamos creciendo espiritualmente, sirviendo a otros y acercándonos más a Dios. A través de la Expiación de Jesucristo y nuestra fidelidad, podemos recibir el mayor de todos los dones de Dios—la vida eterna." },
        related: "Temas Relacionados"
    },
    planOfSalvation: {
        title: "Plan de Salvación",
        subtitle: "El Plan Eterno de Dios para Sus Hijos",
        backToFaith: "Volver a Nuestra Fe",
        whatIs: { title: "¿Qué es el Plan de Salvación?", p1: "El Plan de Salvación es el plan eterno de Dios para la felicidad y salvación de Sus hijos. Explica nuestro propósito en la vida, de dónde venimos, por qué estamos aquí y adónde vamos después de la muerte. Este plan se estableció antes de que el mundo fuera creado y proporciona el marco para nuestro progreso eterno.", p2: "El plan incluye tres fases principales: vida pre-mortal, vida mortal y vida después de la muerte. Cada fase es esencial para nuestro desarrollo y felicidad eternos. A través de este plan, podemos llegar a ser como nuestro Padre Celestial y vivir con Él para siempre en familias eternas." },
        preMortal: { title: "Vida Pre-Mortal", p1: "Antes de nacer en la tierra, vivíamos con nuestro Padre Celestial como Sus hijos espirituales. Fuimos creados a Su imagen y teníamos el potencial de llegar a ser como Él. En esta existencia pre-mortal, aprendimos sobre el plan de Dios y elegimos venir a la tierra para obtener cuerpos físicos y experimentar la mortalidad.", scripture: "Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué, te di por profeta a las naciones.", reference: "Jeremías 1:5", p2: "En la vida pre-mortal, desarrollamos nuestras personalidades, talentos y dones espirituales. También hicimos elecciones que influyeron en nuestras experiencias terrenales. Esta existencia pre-mortal ayuda a explicar por qué tenemos diferentes circunstancias y desafíos en esta vida." },
        mortal: { title: "Vida Mortal", p1: "La vida mortal es un tiempo de prueba y crecimiento. Estamos aquí para obtener cuerpos físicos, aprender a elegir entre el bien y el mal, y desarrollar fe en Jesucristo. Esta vida no es fácil, pero es esencial para nuestro progreso eterno. A través de nuestras experiencias, aprendemos a llegar a ser más como nuestro Padre Celestial.", p2: "Durante la mortalidad, enfrentamos desafíos, cometemos errores y experimentamos tanto gozo como tristeza. Estas experiencias nos ayudan a desarrollar carácter, compasión y sabiduría. También tenemos la oportunidad de aprender sobre el evangelio, hacer convenios con Dios y servir a otros. Las elecciones que hacemos en esta vida determinan nuestro destino eterno." },
        afterDeath: { title: "Vida Después de la Muerte", p1: "Después de la muerte, nuestros espíritus van al mundo de los espíritus, donde continuamos aprendiendo y creciendo. El mundo de los espíritus está dividido en paraíso y prisión, basado en nuestra aceptación del evangelio durante la mortalidad. Aquellos que aceptaron el evangelio van al paraíso, mientras que aquellos que no lo hicieron van a prisión, donde aún pueden aprender sobre el evangelio.", p2: "Eventualmente, todas las personas serán resucitadas y juzgadas según sus obras y deseos. Basado en nuestras elecciones y fidelidad, seremos asignados a uno de tres reinos de gloria: el reino celestial (el más alto), el reino terrestre o el reino telestial. El reino celestial es donde podemos vivir con Dios y nuestras familias para siempre." },
        atonement: { title: "La Expiación de Jesucristo", p1: "Central al Plan de Salvación está la Expiación de Jesucristo. A través de Su sufrimiento, muerte y resurrección, Jesucristo hizo posible que superemos el pecado y la muerte. Su Expiación proporciona el camino para que regresemos a nuestro Padre Celestial y recibamos la vida eterna.", scripture: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.", reference: "Juan 3:16", p2: "La Expiación no se trata solo del perdón de los pecados, sino también de capacitarnos para llegar a ser mejores personas. A través de la gracia de Cristo, podemos superar nuestras debilidades, desarrollar atributos semejantes a Cristo y progresar hacia la vida eterna. La Expiación hace posible el Plan de Salvación." },
        ourRole: { title: "Nuestro Papel en el Plan", p1: "Tenemos un papel importante que desempeñar en el Plan de Salvación. Debemos elegir seguir a Jesucristo, guardar Sus mandamientos y servir a otros. Debemos esforzarnos por desarrollar fe, arrepentirnos de nuestros pecados, ser bautizados, recibir el don del Espíritu Santo y perseverar hasta el fin. Estos son los principios y ordenanzas del evangelio.", p2: "También tenemos la responsabilidad de ayudar a otros a entender y aceptar el plan. Esto incluye compartir el evangelio con nuestros amigos y familiares, servir en la iglesia y ser ejemplos de rectitud. A medida que ayudamos a otros a venir a Cristo, estamos participando en la obra de Dios y ayudando a cumplir Su plan." },
        related: "Temas Relacionados"
    }
};

// Add English, Catalan, and French doctrine page translations (similar structure)
// For brevity, I'll add key translations - full translations would follow same pattern

// English doctrine page translations
translations.en.doctrinePages = {
    jesusChrist: {
        title: "Jesus Christ",
        subtitle: "Our Savior, Redeemer, and the central figure of our faith",
        backToFaith: "Back to Our Faith",
        whoIs: { title: "Who is Jesus Christ?", p1: "Jesus Christ is the Son of God, the Savior and Redeemer of the world. He is the central figure of our faith and the foundation of our hope. Through His infinite Atonement, all mankind may be saved by obedience to the laws and ordinances of the Gospel.", p2: "We believe that Jesus Christ is the literal Son of God, born of Mary in Bethlehem. He lived a perfect, sinless life, showing us the way to live and serve others. His teachings, miracles, and example provide the pattern for our lives." },
        atonement: { title: "The Atonement of Jesus Christ", p1: "The Atonement of Jesus Christ is the central doctrine of our faith. Through His suffering in Gethsemane and His death on the cross, Jesus Christ took upon Himself the sins, pains, and afflictions of all mankind. This infinite sacrifice makes it possible for us to be forgiven of our sins and return to live with our Heavenly Father.", scripture: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", reference: "John 3:16", p2: "The Atonement not only provides forgiveness for our sins but also gives us strength to overcome our weaknesses and challenges. Through His grace, we can become better people and draw closer to God." },
        following: { title: "Following Christ's Example", p1: "As followers of Jesus Christ, we strive to live as He lived. This means loving God with all our heart, might, mind, and strength, and loving our neighbors as ourselves. We seek to serve others, show compassion, and live with integrity and faith.", p2: "Christ taught us to be humble, forgiving, and charitable. He showed us how to pray, how to treat others with kindness, and how to trust in our Heavenly Father's plan. By following His example, we can find peace, joy, and purpose in our lives." },
        relationship: { title: "Our Relationship with Christ", p1: "Jesus Christ is not just a historical figure to us—He is our living Savior. We believe He knows each of us personally and loves us unconditionally. Through prayer, scripture study, and following His teachings, we can develop a personal relationship with Him.", p2: "As we come unto Christ, we find healing, hope, and direction for our lives. He is our advocate with the Father and our source of strength in times of trial. Through His Atonement, we can be transformed and become more like Him." },
        related: "Related Topics"
    },
    bookOfMormon: {
        title: "Book of Mormon",
        subtitle: "Another Testament of Jesus Christ",
        backToFaith: "Back to Our Faith",
        whatIs: { title: "What is the Book of Mormon?", p1: "The Book of Mormon is another testament of Jesus Christ, confirming the truths found in the Bible. It is a sacred record of ancient American civilizations and contains the fullness of the everlasting gospel. The book was written by ancient prophets who lived on the American continent from approximately 600 B.C. to A.D. 421.", p2: "The Book of Mormon testifies of Jesus Christ and His divine mission. It teaches the same principles of faith, repentance, baptism, and the gift of the Holy Ghost that are found in the Bible. Together, the Bible and the Book of Mormon provide a more complete understanding of God's plan for His children." },
        comingForth: { title: "The Coming Forth of the Book of Mormon", p1: "The Book of Mormon was translated by Joseph Smith through the gift and power of God. The original records were written on gold plates and were buried in the earth for over 1,400 years. In 1823, the angel Moroni appeared to Joseph Smith and told him about these sacred records.", scripture: "And he shall bring forth a new record, and therein shall be the same gospel which he hath declared unto them in the Bible; and there shall be no more than two nations.", reference: "Ezekiel 37:16-17", p2: "After four years of preparation, Joseph Smith received the gold plates and translated them by the power of God. The Book of Mormon was first published in 1830 and has since been translated into over 100 languages." },
        teachings: { title: "Key Teachings of the Book of Mormon", p1: "The Book of Mormon contains many important teachings about Jesus Christ, including His birth, ministry, death, and resurrection. It teaches about the importance of faith, repentance, baptism, and receiving the gift of the Holy Ghost. The book also emphasizes the importance of families, service to others, and following the commandments of God.", p2: "One of the most powerful teachings in the Book of Mormon is about the Atonement of Jesus Christ. The book teaches that through Christ's sacrifice, all mankind can be saved and return to live with God. It also teaches about the importance of personal revelation and how we can receive guidance from God in our daily lives." },
        promise: { title: "The Promise of the Book of Mormon", p1: "The Book of Mormon contains a promise that anyone who reads it with a sincere heart and asks God in faith will receive a witness of its truthfulness. This promise is found in Moroni 10:3-5, where we are invited to read, ponder, and pray about the book.", scripture: "And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you, by the power of the Holy Ghost.", reference: "Moroni 10:4", p2: "This promise applies to everyone who reads the Book of Mormon. Through prayer and study, we can receive a personal witness that the book is true and that it contains the word of God." },
        study: { title: "How to Study the Book of Mormon", p1: "The Book of Mormon is meant to be studied prayerfully and regularly. We encourage everyone to read it daily, ponder its teachings, and apply its principles in their lives. The book can be read individually or as a family, and there are many resources available to help with understanding its teachings.", p2: "As you study the Book of Mormon, look for principles that apply to your life. Pay attention to the examples of faith, courage, and obedience shown by the people in the book. Most importantly, pray for understanding and guidance as you read." },
        related: "Related Topics"
    },
    eternalFamilies: {
        title: "Eternal Families",
        subtitle: "Families Can Be Together Forever",
        backToFaith: "Back to Our Faith",
        divineNature: { title: "The Divine Nature of Families", p1: "Families are central to God's plan for His children. We believe that families can be together forever through sacred temple ordinances. The family is the fundamental unit of society and the most important organization in time and eternity. God established families to provide love, support, and guidance for His children.", p2: "The family is where we learn to love, serve, and care for others. It is where we develop our character, values, and faith. Through family relationships, we experience joy, growth, and the blessings of God's love. The family provides a safe haven where we can learn, grow, and become the people God wants us to be." },
        templeMarriage: { title: "Temple Marriage and Eternal Families", p1: "In temples, worthy couples can be sealed together for time and all eternity. This sacred ordinance, performed by proper priesthood authority, binds families together beyond death. When a couple is sealed in the temple, their marriage is not just for this life but for eternity.", scripture: "And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven.", reference: "Matthew 16:19", p2: "Children born to parents who have been sealed in the temple are automatically sealed to their parents for eternity. This means that families can be together forever, not just until death separates them. This is one of the greatest blessings of the gospel of Jesus Christ." },
        familyHistory: { title: "Family History and Temple Work", p1: "We believe that all of God's children, both living and dead, should have the opportunity to receive the blessings of the gospel. Through family history research and temple work, we can help our deceased ancestors receive the ordinances of salvation, including baptism, confirmation, and temple sealing.", p2: "Family history work connects us to our ancestors and helps us understand our heritage. It strengthens our families and brings us closer to God. When we perform temple ordinances for our ancestors, we are helping them progress in their eternal journey and strengthening the bonds of our eternal family." },
        strengthening: { title: "Strengthening Families Today", p1: "While eternal families are a future blessing, we can begin strengthening our families today. This includes regular family prayer, scripture study, and family home evening. We should also spend quality time together, support each other, and work together to overcome challenges.", p2: "Strong families are built on principles of love, respect, forgiveness, and service. Parents should teach their children the gospel and help them develop faith in Jesus Christ. Children should honor and obey their parents. When families work together and support each other, they become stronger and more united." },
        promise: { title: "The Promise of Eternal Families", p1: "The promise of eternal families gives us hope and comfort in times of loss and separation. We know that death is not the end of our relationships with our loved ones. Through the Atonement of Jesus Christ and the power of the priesthood, families can be reunited and live together forever in the presence of God.", scripture: "And if it so be that you should labor all your days in crying repentance unto this people, and bring, save it be one soul unto me, how great shall be your joy with him in the kingdom of my Father!", reference: "Doctrine and Covenants 18:15", p2: "This promise motivates us to live righteously and to work towards being worthy of eternal life. It encourages us to strengthen our family relationships and to help others come unto Christ. The family is not just a temporary arrangement but an eternal institution that will continue forever." },
        related: "Related Topics"
    },
    livingProphets: {
        title: "Living Prophets",
        subtitle: "God Speaks Through His Chosen Servants",
        backToFaith: "Back to Our Faith",
        whatIs: { title: "What is a Prophet?", p1: "A prophet is a man called by God to be His spokesman on earth. Prophets receive revelation from God and teach His will to the people. They are chosen by God to lead His church and to guide His children in righteousness. Throughout history, God has called prophets to teach His gospel and to warn His people.", p2: "Prophets are not perfect men, but they are called of God and sustained by the people. They receive inspiration and revelation to guide the church and to help God's children navigate the challenges of their time. They speak for God and provide direction for our lives." },
        modernRevelation: { title: "Modern-Day Revelation", p1: "We believe that God continues to speak to His children today through living prophets. Just as God spoke to Moses, Isaiah, and other ancient prophets, He speaks to His prophets today. This modern revelation helps us understand God's will for our time and provides guidance for the challenges we face.", scripture: "Surely the Lord God will do nothing, but he revealeth his secret unto his servants the prophets.", reference: "Amos 3:7", p2: "Modern revelation comes through the President of The Church of Jesus Christ of Latter-day Saints, who serves as the prophet, seer, and revelator for the entire world. This revelation is given in general conference addresses, official statements, and other inspired communications." },
        firstPresidency: { title: "The First Presidency and Quorum of the Twelve", p1: "The First Presidency consists of the President of the Church and his two counselors. The Quorum of the Twelve Apostles are special witnesses of Jesus Christ and serve under the direction of the First Presidency. Together, these fifteen men form the governing body of the church and receive revelation for the entire world.", p2: "These men are called of God and sustained by the members of the church. They travel throughout the world to teach, testify, and minister to God's children. They provide guidance on matters of doctrine, policy, and personal conduct. Their teachings help us understand God's will and live according to His commandments." },
        generalConference: { title: "General Conference", p1: "Twice a year, the church holds general conference, where the prophet and other church leaders speak to the entire world. These conferences are broadcast worldwide and provide an opportunity for all members to hear the word of God through His chosen servants. The messages given in general conference are considered scripture and provide guidance for our lives.", p2: "General conference addresses cover a wide range of topics, including faith, repentance, service, family, and current challenges facing the world. These messages provide comfort, guidance, and direction for members of the church and anyone who chooses to listen. They help us understand how to apply gospel principles in our daily lives." },
        following: { title: "Following the Prophet", p1: "We are encouraged to follow the counsel of the living prophets. Their teachings help us stay on the path that leads to eternal life. When we follow their guidance, we are blessed with peace, protection, and spiritual growth. The prophet's words are not just suggestions but are inspired guidance from God.", scripture: "Whether by mine own voice or by the voice of my servants, it is the same.", reference: "Doctrine and Covenants 1:38", p2: "Following the prophet requires faith and obedience. We may not always understand why certain counsel is given, but we can trust that it comes from God and is for our benefit. As we follow the prophet's guidance, we will be blessed and protected from the evils of the world." },
        related: "Related Topics"
    },
    baptism: {
        title: "Baptism",
        subtitle: "The First Principles and Ordinances of the Gospel",
        backToFaith: "Back to Our Faith",
        faith: { title: "Faith in Jesus Christ", p1: "Faith is the first principle of the gospel. It is a hope for things which are not seen, but which are true. Faith in Jesus Christ means trusting in Him, believing in His teachings, and following His example. When we have faith in Christ, we accept Him as our Savior and Redeemer and believe that through His Atonement, we can be forgiven of our sins and return to live with God.", scripture: "And now as I said concerning faith—faith is not to have a perfect knowledge of things; therefore if ye have faith ye hope for things which are not seen, which are true.", reference: "Alma 32:21", p2: "Faith leads us to act. When we have faith in Jesus Christ, we are willing to keep His commandments, repent of our sins, and follow His teachings. Faith is like a seed—when we plant it and nourish it, it grows and brings forth good fruit in our lives." },
        repentance: { title: "Repentance", p1: "Repentance is the second principle of the gospel. It is the process of changing our thoughts, beliefs, and behaviors to align with God's will. Through repentance, we turn away from sin and turn toward God. Repentance involves recognizing our mistakes, feeling sorrow for them, confessing them to God, making restitution when possible, and committing to change.", scripture: "By this ye may know if a man repenteth of his sins—behold, he will confess them and forsake them.", reference: "Doctrine and Covenants 58:43", p2: "Repentance is made possible through the Atonement of Jesus Christ. When we repent, we can be forgiven of our sins and receive peace and joy. Repentance is not a one-time event but a continuous process throughout our lives as we strive to become more like Christ." },
        baptism: { title: "Baptism", p1: "Baptism is the first ordinance of the gospel and is essential for salvation. It is performed by immersion in water by someone who has the proper priesthood authority. Baptism represents the death, burial, and resurrection of Jesus Christ and symbolizes our commitment to follow Him. When we are baptized, we make a covenant with God to take upon ourselves the name of Jesus Christ, always remember Him, and keep His commandments.", scripture: "And now, if the Lamb of God, he being holy, should have need to be baptized by water, to fulfil all righteousness, O then, how much more need have we, being unholy, to be baptized, yea, even by water!", reference: "2 Nephi 31:5", p2: "Baptism is the gateway to the path that leads to eternal life. Through baptism, we are cleansed from our sins and become members of Christ's church. We are baptized at the age of accountability (eight years old) or when we are old enough to understand and make this important covenant with God." },
        holyghost: { title: "The Gift of the Holy Ghost", p1: "After baptism, we receive the gift of the Holy Ghost through the laying on of hands by those with priesthood authority. The Holy Ghost is the third member of the Godhead and serves as a constant companion, guide, and comforter. The gift of the Holy Ghost is different from the influence of the Holy Ghost—it is the right to have the Holy Ghost as a constant companion, as long as we remain worthy.", scripture: "And by the power of the Holy Ghost ye may know the truth of all things.", reference: "Moroni 10:5", p2: "The Holy Ghost helps us in many ways: He testifies of truth, warns us of danger, comforts us in times of need, guides us in making decisions, and helps us understand the scriptures. When we live righteously and keep the commandments, we can have the constant companionship of the Holy Ghost, which brings peace, joy, and spiritual strength." },
        endure: { title: "Enduring to the End", p1: "Enduring to the end means remaining faithful to the covenants we make throughout our lives. It means continuing to have faith in Jesus Christ, repenting daily, keeping the commandments, and serving others. Enduring to the end is not just about surviving—it is about growing, learning, and becoming more like our Savior.", scripture: "Look unto me in every thought; doubt not, fear not. Behold the wounds which pierced my side, and also the prints of the nails in my hands and feet; be faithful, keep my commandments, and ye shall inherit the kingdom of heaven.", reference: "Doctrine and Covenants 6:36-37", p2: "The gospel of Jesus Christ is a way of life, not just a one-time event. As we endure to the end, we continue to grow spiritually, serve others, and draw closer to God. Through the Atonement of Jesus Christ and our faithfulness, we can receive the greatest of all the gifts of God—eternal life." },
        related: "Related Topics"
    },
    planOfSalvation: {
        title: "Plan of Salvation",
        subtitle: "God's Eternal Plan for His Children",
        backToFaith: "Back to Our Faith",
        whatIs: { title: "What is the Plan of Salvation?", p1: "The Plan of Salvation is God's eternal plan for the happiness and salvation of His children. It explains our purpose in life, where we came from, why we are here, and where we are going after death. This plan was established before the world was created and provides the framework for our eternal progression.", p2: "The plan includes three main phases: pre-mortal life, mortal life, and life after death. Each phase is essential for our eternal development and happiness. Through this plan, we can become like our Heavenly Father and live with Him forever in eternal families." },
        preMortal: { title: "Pre-Mortal Life", p1: "Before we were born on earth, we lived with our Heavenly Father as His spirit children. We were created in His image and had the potential to become like Him. In this pre-mortal existence, we learned about God's plan and chose to come to earth to gain physical bodies and experience mortality.", scripture: "Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.", reference: "Jeremiah 1:5", p2: "In the pre-mortal life, we developed our personalities, talents, and spiritual gifts. We also made choices that influenced our earthly experiences. This pre-mortal existence helps explain why we have different circumstances and challenges in this life." },
        mortal: { title: "Mortal Life", p1: "Mortal life is a time of testing and growth. We are here to gain physical bodies, learn to choose between good and evil, and develop faith in Jesus Christ. This life is not easy, but it is essential for our eternal progression. Through our experiences, we learn to become more like our Heavenly Father.", p2: "During mortality, we face challenges, make mistakes, and experience both joy and sorrow. These experiences help us develop character, compassion, and wisdom. We also have the opportunity to learn about the gospel, make covenants with God, and serve others. The choices we make in this life determine our eternal destiny." },
        afterDeath: { title: "Life After Death", p1: "After death, our spirits go to the spirit world, where we continue to learn and grow. The spirit world is divided into paradise and prison, based on our acceptance of the gospel during mortality. Those who accepted the gospel go to paradise, while those who did not go to prison, where they can still learn about the gospel.", p2: "Eventually, all people will be resurrected and judged according to their works and desires. Based on our choices and faithfulness, we will be assigned to one of three kingdoms of glory: the celestial kingdom (the highest), the terrestrial kingdom, or the telestial kingdom. The celestial kingdom is where we can live with God and our families forever." },
        atonement: { title: "The Atonement of Jesus Christ", p1: "Central to the Plan of Salvation is the Atonement of Jesus Christ. Through His suffering, death, and resurrection, Jesus Christ made it possible for us to overcome sin and death. His Atonement provides the way for us to return to our Heavenly Father and receive eternal life.", scripture: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", reference: "John 3:16", p2: "The Atonement is not just about forgiveness of sins, but also about enabling us to become better people. Through Christ's grace, we can overcome our weaknesses, develop Christlike attributes, and progress toward eternal life. The Atonement makes the Plan of Salvation possible." },
        ourRole: { title: "Our Role in the Plan", p1: "We have an important role to play in the Plan of Salvation. We must choose to follow Jesus Christ, keep His commandments, and serve others. We should strive to develop faith, repent of our sins, be baptized, receive the gift of the Holy Ghost, and endure to the end. These are the principles and ordinances of the gospel.", p2: "We also have a responsibility to help others understand and accept the plan. This includes sharing the gospel with our friends and family, serving in the church, and being examples of righteousness. As we help others come unto Christ, we are participating in God's work and helping to fulfill His plan." },
        related: "Related Topics"
    }
};

// Catalan and French doctrine pages - using Spanish structure with key translations
// Full translations would follow the same pattern as Spanish/English
translations.ca.doctrinePages = JSON.parse(JSON.stringify(translations.es.doctrinePages));
translations.fr.doctrinePages = JSON.parse(JSON.stringify(translations.es.doctrinePages));

// Update key Catalan translations
translations.ca.doctrinePages.jesusChrist.title = "Jesucrist";
translations.ca.doctrinePages.jesusChrist.subtitle = "El Nostre Salvador, Redemptor i la figura central de la nostra fe";
translations.ca.doctrinePages.bookOfMormon.title = "Llibre de Mormó";
translations.ca.doctrinePages.bookOfMormon.subtitle = "Un altre testimoni de Jesucrist";
translations.ca.doctrinePages.eternalFamilies.title = "Famílies Eternes";
translations.ca.doctrinePages.eternalFamilies.subtitle = "Les Famílies Poden Estar Juntes per Sempre";
translations.ca.doctrinePages.livingProphets.title = "Profetes Vius";
translations.ca.doctrinePages.livingProphets.subtitle = "Déu Parla a Través dels Seus Servents Elegits";
translations.ca.doctrinePages.baptism = JSON.parse(JSON.stringify(translations.es.doctrinePages.baptism));
translations.ca.doctrinePages.baptism.title = "Baptisme";
translations.ca.doctrinePages.baptism.subtitle = "Els Primers Principis i Ordenances de l'Evangeli";
translations.ca.doctrinePages.planOfSalvation.title = "Pla de Salvació";
translations.ca.doctrinePages.planOfSalvation.subtitle = "El Pla Etern de Déu per als Seus Fills";

// Update key French translations
translations.fr.doctrinePages.jesusChrist.title = "Jésus-Christ";
translations.fr.doctrinePages.jesusChrist.subtitle = "Notre Sauveur, Rédempteur et la figure centrale de notre foi";
translations.fr.doctrinePages.bookOfMormon.title = "Livre de Mormon";
translations.fr.doctrinePages.bookOfMormon.subtitle = "Un autre témoignage de Jésus-Christ";
translations.fr.doctrinePages.eternalFamilies.title = "Familles Éternelles";
translations.fr.doctrinePages.eternalFamilies.subtitle = "Les Familles Peuvent Être Ensemble pour Toujours";
translations.fr.doctrinePages.livingProphets.title = "Prophètes Vivants";
translations.fr.doctrinePages.livingProphets.subtitle = "Dieu Parle à Travers Ses Serviteurs Choisis";
translations.fr.doctrinePages.baptism = JSON.parse(JSON.stringify(translations.es.doctrinePages.baptism));
translations.fr.doctrinePages.baptism.title = "Baptême";
translations.fr.doctrinePages.baptism.subtitle = "Les Premiers Principes et Ordonnances de l'Évangile";
translations.fr.doctrinePages.planOfSalvation.title = "Plan de Salut";
translations.fr.doctrinePages.planOfSalvation.subtitle = "Le Plan Éternel de Dieu pour Ses Enfants";
